[build]
  base = "todo-app-frontend"  # where the code and package.json are located
  command = "npm run build"  # build command for React app
  publish = "todo-app-frontend/build"  # location of the build output

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
